In [94]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

##### Problemi:
Da li vozač osvaja bodove tokom trke ili ne?<br>
Da li će vozač u narednom krugu da izgubi, osvoji ili ostane na istoj poziciji?<br>
Određivanje vremena narednog kruga.

# Loading data

In [95]:
circuits = pd.read_csv('data/circuits.csv')
constructor_results = pd.read_csv('data/constructor_results.csv')
constructor_standings = pd.read_csv('data/constructor_standings.csv')
constructors = pd.read_csv('data/constructors.csv')
driver_standings = pd.read_csv('data/driver_standings.csv')
drivers = pd.read_csv('data/drivers.csv')
lap_times = pd.read_csv('data/lap_times.csv')
pit_stops = pd.read_csv('data/pit_stops.csv')
qualifying = pd.read_csv('data/qualifying.csv')
races = pd.read_csv('data/races.csv')
results = pd.read_csv('data/results.csv')
seasons = pd.read_csv('data/seasons.csv')
sprint_results = pd.read_csv('data/sprint_results.csv')
status = pd.read_csv('data/status.csv')

# Understanding, refining and cleaning data

In [96]:
drivers.tail(50)
#drivers[drivers['driverId'] == 830]

driverId          driverRef number code   forename        surname  \
811       812           chandhok     \N  CHA      Karun       Chandhok   
812       813          maldonado     13  MAL     Pastor      Maldonado   
813       814              resta     40  DIR       Paul       di Resta   
814       815              perez     11  PER     Sergio          Pérez   
815       816           ambrosio     \N  DAM     Jérôme     d'Ambrosio   
816       817          ricciardo      3  RIC     Daniel      Ricciardo   
817       818             vergne     25  VER  Jean-Éric         Vergne   
818       819                pic     \N  PIC    Charles            Pic   
819       820            chilton      4  CHI        Max        Chilton   
820       821          gutierrez     21  GUT    Esteban      Gutiérrez   
821       822             bottas     77  BOT   Valtteri         Bottas   
822       823              garde     \N  VDG      Giedo  van der Garde   
823       824      jules_bianchi     17  BIA      Jules        Bianchi   
824       825    kevin_magnussen     20  MAG      Kevin      Magnussen   
825       826              kvyat     26  KVY     Daniil          Kvyat   
826       827           lotterer     45  LOT      André       Lotterer   
827       828           ericsson      9  ERI     Marcus       Ericsson   
828       829            stevens     28  STE       Will        Stevens   
829       830     max_verstappen     33  VER        Max     Verstappen   
830       831               nasr     12  NAS     Felipe           Nasr   
831       832              sainz     55  SAI     Carlos          Sainz   
832       833              merhi     98  MER    Roberto          Merhi   
833       834              rossi     53  RSS  Alexander          Rossi   
834       835      jolyon_palmer     30  PAL     Jolyon         Palmer   
835       836           wehrlein     94  WEH     Pascal       Wehrlein   
836       837           haryanto     88  HAR        Rio       Haryanto   
837       838          vandoorne      2  VAN    Stoffel      Vandoorne   
838       839               ocon     31  OCO    Esteban           Ocon   
839       840             stroll     18  STR      Lance         Stroll   
840       841         giovinazzi     99  GIO    Antonio     Giovinazzi   
841       843    brendon_hartley     28  HAR    Brendon        Hartley   
842       844            leclerc     16  LEC    Charles        Leclerc   
843       845           sirotkin     35  SIR     Sergey       Sirotkin   
844       846             norris      4  NOR      Lando         Norris   
845       847            russell     63  RUS     George        Russell   
846       848              albon     23  ALB  Alexander          Albon   
847       849             latifi      6  LAT   Nicholas         Latifi   
848       850  pietro_fittipaldi     51  FIT     Pietro     Fittipaldi   
849       851             aitken     89  AIT       Jack         Aitken   
850       852            tsunoda     22  TSU       Yuki        Tsunoda   
851       853            mazepin      9  MAZ     Nikita        Mazepin   
852       854    mick_schumacher     47  MSC       Mick     Schumacher   
853       855               zhou     24  ZHO     Guanyu           Zhou   
854       856           de_vries     21  DEV       Nyck       de Vries   
855       857            piastri     81  PIA      Oscar        Piastri   
856       858           sargeant      2  SAR      Logan       Sargeant   
857       859             lawson     30  LAW       Liam         Lawson   
858       860            bearman     38  BEA     Oliver        Bearman   
859       861          colapinto     43  COL     Franco      Colapinto   
860       862             doohan     61  DOO       Jack         Doohan   

            dob    nationality  \
811  1984-01-19         Indian   
812  1985-03-09     Venezuelan   
813  1986-04-16        British   
814  1990-01-26        Mexican   
815  1985-12-27        Belgian   
816  1989-07-01     Austra

In [97]:
races = races[races['year'] >= 2020]

In [98]:
races.head(10)

raceId  year  round  circuitId                         name        date  \
1018    1031  2020      1         70          Austrian Grand Prix  2020-07-05   
1019    1032  2020      2         70           Styrian Grand Prix  2020-07-12   
1020    1033  2020      3         11         Hungarian Grand Prix  2020-07-19   
1021    1034  2020      4          9           British Grand Prix  2020-08-02   
1022    1035  2020      5          9  70th Anniversary Grand Prix  2020-08-09   
1023    1036  2020      6          4           Spanish Grand Prix  2020-08-16   
1024    1037  2020      7         13           Belgian Grand Prix  2020-08-30   
1025    1038  2020      8         14           Italian Grand Prix  2020-09-06   
1026    1039  2020      9         76            Tuscan Grand Prix  2020-09-13   
1027    1040  2020     10         71           Russian Grand Prix  2020-09-27   

          time                                                url fp1_date  \
1018  13:10:00  http://en.wikipedia.org/wiki/2020_Austrian_Gra...       \N   
1019  13:10:00  http://en.wikipedia.org/wiki/2020_Styrian_Gran...       \N   
1020  13:10:00  http://en.wikipedia.org/wiki/2020_Hungarian_Gr...       \N   
1021  13:10:00  http://en.wikipedia.org/wiki/2020_British_Gran...       \N   
1022  13:10:00  http://en.wikipedia.org/wiki/70th_Anniversary_...       \N   
1023  13:10:00  http://en.wikipedia.org/wiki/2020_Spanish_Gran...       \N   
1024  13:10:00  http://en.wikipedia.org/wiki/2020_Belgian_Gran...       \N   
1025  13:10:00  http://en.wikipedia.org/wiki/2020_Italian_Gran...       \N   
1026  13:10:00  http://en.wikipedia.org/wiki/2020_Tuscan_Grand...       \N   
1027  11:10:00  http://en.wikipedia.org/wiki/2020_Russian_Gran...       \N   

     fp1_time fp2_date fp2_time fp3_date fp3_time quali_date quali_time  \
1018       \N       \N       \N       \N       \N         \N         \N   
1019       \N       \N       \N       \N       \N         \N         \N   
1020       \N       \N       \N       \N       \N         \N         \N   
1021       \N       \N       \N       \N       \N         \N         \N   
1022       \N       \N       \N       \N       \N         \N         \N   
1023       \N       \N       \N       \N       \N         \N         \N   
1024       \N       \N       \N       \N       \N         \N         \N   
1025       \N       \N       \N       \N       \N         \N         \N   
1026       \N       \N       \N       \N       \N         \N         \N   
1027       \N       \N       \N       \N       \N         \N         \N   

     sprint_date sprint_time  
1018          \N          \N  
1019          \N          \N  
1020          \N          \N  
1021          \N          \N  
1022          \N          \N  
1023          \N          \N  
1024          \N          \N  
1025          \N          \N  
1026          \N          \N  
1027          \N          \N

In [99]:
cols = ['raceId', 'circuitId', 'year', 'round', 'name', 'date', 'time']
df = races[cols]
print(df.shape)

(107, 7)


1031 je prva trka u 2020. godini

Spajamo left, što znači da uzimamo samo iz df skupa raceId, i spajamo sa raceId iz quali

In [100]:
df = df.merge(qualifying, on='raceId', how='left')

In [101]:
print(df.shape)
df['grid'] = df['position']
df = df.drop(columns='position')
df.head()

(2138, 15)


raceId  circuitId  year  round                 name        date      time  \
0    1031         70  2020      1  Austrian Grand Prix  2020-07-05  13:10:00   
1    1031         70  2020      1  Austrian Grand Prix  2020-07-05  13:10:00   
2    1031         70  2020      1  Austrian Grand Prix  2020-07-05  13:10:00   
3    1031         70  2020      1  Austrian Grand Prix  2020-07-05  13:10:00   
4    1031         70  2020      1  Austrian Grand Prix  2020-07-05  13:10:00   

   qualifyId  driverId  constructorId  number        q1        q2        q3  \
0       8378       822            131      77  1:04.111  1:03.015  1:02.939   
1       8379         1            131      44  1:04.198  1:03.096  1:02.951   
2       8380       830              9      33  1:04.024  1:04.000  1:03.477   
3       8381       846              1       4  1:04.606  1:03.819  1:03.626   
4       8382       848              9      23  1:04.661  1:03.746  1:03.868   

   grid  
0     1  
1     2  
2     3  
3     4  
4     5

Ovde cemo da uzmemo deo constructor_standings i driver_standings skupova gde su podaci noviji od 12.2019. godine. Posto red u ovim kolonama predstavlja situaciju nakon trke, mi ćemo da kreiramo nove kolone koje će za posmatranu trku (raceId) da gledaju prethodne rezultate - tj. nakon prethodne trke - tj. pre posmatrane.

In [102]:
races.head()

raceId  year  round  circuitId                         name        date  \
1018    1031  2020      1         70          Austrian Grand Prix  2020-07-05   
1019    1032  2020      2         70           Styrian Grand Prix  2020-07-12   
1020    1033  2020      3         11         Hungarian Grand Prix  2020-07-19   
1021    1034  2020      4          9           British Grand Prix  2020-08-02   
1022    1035  2020      5          9  70th Anniversary Grand Prix  2020-08-09   

          time                                                url fp1_date  \
1018  13:10:00  http://en.wikipedia.org/wiki/2020_Austrian_Gra...       \N   
1019  13:10:00  http://en.wikipedia.org/wiki/2020_Styrian_Gran...       \N   
1020  13:10:00  http://en.wikipedia.org/wiki/2020_Hungarian_Gr...       \N   
1021  13:10:00  http://en.wikipedia.org/wiki/2020_British_Gran...       \N   
1022  13:10:00  http://en.wikipedia.org/wiki/70th_Anniversary_...       \N   

     fp1_time fp2_date fp2_time fp3_date fp3_time quali_date quali_time  \
1018       \N       \N       \N       \N       \N         \N         \N   
1019       \N       \N       \N       \N       \N         \N         \N   
1020       \N       \N       \N       \N       \N         \N         \N   
1021       \N       \N       \N       \N       \N         \N         \N   
1022       \N       \N       \N       \N       \N         \N         \N   

     sprint_date sprint_time  
1018          \N          \N  
1019          \N          \N  
1020          \N          \N  
1021          \N          \N  
1022          \N          \N

In [103]:
driver_standings = driver_standings[driver_standings['raceId'] >= 1031]
constructor_standings = constructor_standings[constructor_standings['raceId'] >= 1031]

In [104]:
print('Constructor standings shape: ', constructor_standings.shape)
print('Driver standings shape: ', driver_standings.shape)
driver_standings.head()

Constructor standings shape:  (1070, 7)
Driver standings shape:  (2256, 7)


driverStandingsId  raceId  driverId  points  position positionText  \
32566              69888    1034       830    52.0         3            3   
32567              69887    1034       817    20.0         9            9   
32568              69886    1034       840    20.0         8            8   
32569              69885    1034       825     1.0        16           16   
32570              69884    1034       154     0.0        20           20   

       wins  
32566     0  
32567     0  
32568     0  
32569     0  
32570     0

In [105]:
driver_standings = driver_standings.sort_values(by=['driverId', 'raceId'])
constructor_standings = constructor_standings.sort_values(by=['constructorId', 'raceId'])

In [106]:
driver_standings['before_race_points'] = driver_standings.groupby('driverId')['points'].shift(1)
driver_standings['before_race_position'] = driver_standings.groupby('driverId')['position'].shift(1)
driver_standings['before_race_wins'] = driver_standings.groupby('driverId')['wins'].shift(1)

driver_standings.loc[driver_standings['raceId'] == 1031, ['before_race_points',	'before_race_position',	'before_race_wins']] = [0, 0, 0]

driver_standings.head(10)

driverStandingsId  raceId  driverId  points  position positionText  \
32604              69998    1031         1    12.0         4            4   
32611              69812    1032         1    37.0         2            2   
32637              69852    1033         1    63.0         1            1   
32582              69872    1034         1    88.0         1            1   
32652              69893    1035         1   107.0         1            1   
32673              69914    1036         1   132.0         1            1   
32694              69935    1037         1   157.0         1            1   
32715              69956    1038         1   164.0         1            1   
32736              69977    1039         1   190.0         1            1   
32755              70018    1040         1   205.0         1            1   

       wins  before_race_points  before_race_position  before_race_wins  
32604     0                 0.0                   0.0               0.0  
32611     1                12.0                   4.0               0.0  
32637     2                37.0                   2.0               1.0  
32582     3                63.0                   1.0               2.0  
32652     3                88.0                   1.0               3.0  
32673     4               107.0                   1.0               3.0  
32694     5               132.0                   1.0               4.0  
32715     5               157.0                   1.0               5.0  
32736     6               164.0                   1.0               5.0  
32755     6               190.0                   1.0               6.0

In [107]:
constructor_standings['before_race_ctor_points'] = constructor_standings.groupby('constructorId')['points'].shift(1)
constructor_standings['before_race_ctor_position'] = constructor_standings.groupby('constructorId')['position'].shift(1)
constructor_standings['before_race_ctor_wins'] = constructor_standings.groupby('constructorId')['wins'].shift(1)

constructor_standings.loc[constructor_standings['raceId'] == 1031, ['before_race_ctor_points', 'before_race_ctor_position', 'before_race_ctor_wins']] = [0, 0, 0]

constructor_standings.head(10)

constructorStandingsId  raceId  constructorId  points  position  \
12334                   27575    1031              1    26.0         2   
12339                   27485    1032              1    39.0         2   
12353                   27505    1033              1    41.0         3   
12323                   27515    1034              1    51.0         3   
12359                   27525    1035              1    53.0         4   
12369                   27535    1036              1    62.0         4   
12379                   27545    1037              1    68.0         3   
12389                   27555    1038              1    98.0         3   
12399                   27565    1039              1   106.0         3   
12408                   27585    1040              1   106.0         3   

      positionText  wins  before_race_ctor_points  before_race_ctor_position  \
12334            2     0                      0.0                        0.0   
12339            2     0                     26.0                        2.0   
12353            3     0                     39.0                        2.0   
12323            3     0                     41.0                        3.0   
12359            4     0                     51.0                        3.0   
12369            4     0                     53.0                        4.0   
12379            3     0                     62.0                        4.0   
12389            3     0                     68.0                        3.0   
12399            3     0                     98.0                        3.0   
12408            3     0                    106.0                        3.0   

       before_race_ctor_wins  
12334                    0.0  
12339                    0.0  
12353                    0.0  
12323                    0.0  
12359                    0.0  
12369                    0.0  
12379                    0.0  
12389                    0.0  
12399                    0.0  
12408                    0.0

In [108]:
driver_features = driver_standings[['raceId', 'driverId', 'before_race_points', 'before_race_position', 'before_race_wins']]
constructor_features = constructor_standings[['raceId', 'constructorId', 'before_race_ctor_points', 'before_race_ctor_position', 
                                                                                                    'before_race_ctor_wins']]

In [109]:
df = df.merge(driver_features, on=['raceId', 'driverId'], how='left')
df = df.merge(constructor_features, on=['raceId', 'constructorId'], how='left')

In [110]:
print(df.shape)
df.head(5)

(2138, 21)


raceId  circuitId  year  round                 name        date      time  \
0    1031         70  2020      1  Austrian Grand Prix  2020-07-05  13:10:00   
1    1031         70  2020      1  Austrian Grand Prix  2020-07-05  13:10:00   
2    1031         70  2020      1  Austrian Grand Prix  2020-07-05  13:10:00   
3    1031         70  2020      1  Austrian Grand Prix  2020-07-05  13:10:00   
4    1031         70  2020      1  Austrian Grand Prix  2020-07-05  13:10:00   

   qualifyId  driverId  constructorId  number        q1        q2        q3  \
0       8378       822            131      77  1:04.111  1:03.015  1:02.939   
1       8379         1            131      44  1:04.198  1:03.096  1:02.951   
2       8380       830              9      33  1:04.024  1:04.000  1:03.477   
3       8381       846              1       4  1:04.606  1:03.819  1:03.626   
4       8382       848              9      23  1:04.661  1:03.746  1:03.868   

   grid  before_race_points  before_race_position  before_race_wins  \
0     1                 0.0                   0.0               0.0   
1     2                 0.0                   0.0               0.0   
2     3                 0.0                   0.0               0.0   
3     4                 0.0                   0.0               0.0   
4     5                 0.0                   0.0               0.0   

   before_race_ctor_points  before_race_ctor_position  before_race_ctor_wins  
0                      0.0                        0.0                    0.0  
1                      0.0                        0.0                    0.0  
2                      0.0                        0.0                    0.0  
3                      0.0                        0.0                    0.0  
4                      0.0                        0.0                    0.0

Spajamo df sa drivers da bismo dobili datum rođenja, da bismo napravili feature broj godina.

In [111]:
drivers_red = drivers[['driverId', 'dob']]

In [112]:
df = df.merge(drivers_red, on='driverId', how='left')

In [113]:
df.head(3)

raceId  circuitId  year  round                 name        date      time  \
0    1031         70  2020      1  Austrian Grand Prix  2020-07-05  13:10:00   
1    1031         70  2020      1  Austrian Grand Prix  2020-07-05  13:10:00   
2    1031         70  2020      1  Austrian Grand Prix  2020-07-05  13:10:00   

   qualifyId  driverId  constructorId  number        q1        q2        q3  \
0       8378       822            131      77  1:04.111  1:03.015  1:02.939   
1       8379         1            131      44  1:04.198  1:03.096  1:02.951   
2       8380       830              9      33  1:04.024  1:04.000  1:03.477   

   grid  before_race_points  before_race_position  before_race_wins  \
0     1                 0.0                   0.0               0.0   
1     2                 0.0                   0.0               0.0   
2     3                 0.0                   0.0               0.0   

   before_race_ctor_points  before_race_ctor_position  before_race_ctor_wins  \
0                      0.0                        0.0                    0.0   
1                      0.0                        0.0                    0.0   
2                      0.0                        0.0                    0.0   

          dob  
0  1989-08-28  
1  1985-01-07  
2  1997-09-30

Za name - nazive staza ne postoje null vrednosti tj. na ili nešto slično. Pomoću metode unique() sam proverio i dobijam isključivo nazive staza.

In [114]:
df['name'].unique()

array(['Austrian Grand Prix', 'Styrian Grand Prix',
       'Hungarian Grand Prix', 'British Grand Prix',
       '70th Anniversary Grand Prix', 'Spanish Grand Prix',
       'Belgian Grand Prix', 'Italian Grand Prix', 'Tuscan Grand Prix',
       'Russian Grand Prix', 'Eifel Grand Prix', 'Portuguese Grand Prix',
       'Emilia Romagna Grand Prix', 'Turkish Grand Prix',
       'Bahrain Grand Prix', 'Sakhir Grand Prix', 'Abu Dhabi Grand Prix',
       'Qatar Grand Prix', 'Monaco Grand Prix', 'Azerbaijan Grand Prix',
       'French Grand Prix', 'Dutch Grand Prix',
       'United States Grand Prix', 'Mexico City Grand Prix',
       'São Paulo Grand Prix', 'Saudi Arabian Grand Prix',
       'Australian Grand Prix', 'Miami Grand Prix', 'Canadian Grand Prix',
       'Singapore Grand Prix', 'Japanese Grand Prix',
       'Las Vegas Grand Prix', 'Chinese Grand Prix'], dtype=object)

In [115]:
df['date'] = pd.to_datetime(df['date'])
df['dob'] = pd.to_datetime(df['dob'])
print(df.dtypes)
df.head()

raceId                                int64
circuitId                             int64
year                                  int64
round                                 int64
name                                 object
date                         datetime64[ns]
time                                 object
qualifyId                             int64
driverId                              int64
constructorId                         int64
number                                int64
q1                                   object
q2                                   object
q3                                   object
grid                                  int64
before_race_points                  float64
before_race_position                float64
before_race_wins                    float64
before_race_ctor_points             float64
before_race_ctor_position           float64
before_race_ctor_wins               float64
dob                          datetime64[ns]
dtype: object


raceId  circuitId  year  round                 name       date      time  \
0    1031         70  2020      1  Austrian Grand Prix 2020-07-05  13:10:00   
1    1031         70  2020      1  Austrian Grand Prix 2020-07-05  13:10:00   
2    1031         70  2020      1  Austrian Grand Prix 2020-07-05  13:10:00   
3    1031         70  2020      1  Austrian Grand Prix 2020-07-05  13:10:00   
4    1031         70  2020      1  Austrian Grand Prix 2020-07-05  13:10:00   

   qualifyId  driverId  constructorId  number        q1        q2        q3  \
0       8378       822            131      77  1:04.111  1:03.015  1:02.939   
1       8379         1            131      44  1:04.198  1:03.096  1:02.951   
2       8380       830              9      33  1:04.024  1:04.000  1:03.477   
3       8381       846              1       4  1:04.606  1:03.819  1:03.626   
4       8382       848              9      23  1:04.661  1:03.746  1:03.868   

   grid  before_race_points  before_race_position  before_race_wins  \
0     1                 0.0                   0.0               0.0   
1     2                 0.0                   0.0               0.0   
2     3                 0.0                   0.0               0.0   
3     4                 0.0                   0.0               0.0   
4     5                 0.0                   0.0               0.0   

   before_race_ctor_points  before_race_ctor_position  before_race_ctor_wins  \
0                      0.0                        0.0                    0.0   
1                      0.0                        0.0                    0.0   
2                      0.0                        0.0                    0.0   
3                      0.0                        0.0                    0.0   
4                      0.0                        0.0                    0.0   

         dob  
0 1989-08-28  
1 1985-01-07  
2 1997-09-30  
3 1999-11-13  
4 1996-03-23

In [116]:
def time_to_miliseconds(t):
    if pd.isna(t):
        return None
    try:
        parts = t.split(':')
        minutes = int(parts[0])
        seconds = float(parts[1])
        total_ms = (minutes * 60 + seconds) * 1000
        return int(total_ms)
    except:
        return None

In [117]:
df['race_time_ms'] = df['time'].apply(time_to_miliseconds)
df['q1_ms'] = df['q1'].apply(time_to_miliseconds)
df['q2_ms'] = df['q2'].apply(time_to_miliseconds)
df['q3_ms'] = df['q3'].apply(time_to_miliseconds)

In [118]:
df['driver_age'] = (df['date'] - df['dob']).dt.days / 365.25

In [119]:
df = df.replace("\\N", np.nan)
print(df.isna().sum())

raceId                          0
circuitId                       0
year                            0
round                           0
name                            0
date                            0
time                            0
qualifyId                       0
driverId                        0
constructorId                   0
number                          0
q1                             21
q2                            551
q3                           1093
grid                            0
before_race_points             15
before_race_position           15
before_race_wins               15
before_race_ctor_points         8
before_race_ctor_position       8
before_race_ctor_wins           8
dob                             0
race_time_ms                    0
q1_ms                          21
q2_ms                         551
q3_ms                        1093
driver_age                      0
dtype: int64


In [120]:
df.head()

raceId  circuitId  year  round                 name       date      time  \
0    1031         70  2020      1  Austrian Grand Prix 2020-07-05  13:10:00   
1    1031         70  2020      1  Austrian Grand Prix 2020-07-05  13:10:00   
2    1031         70  2020      1  Austrian Grand Prix 2020-07-05  13:10:00   
3    1031         70  2020      1  Austrian Grand Prix 2020-07-05  13:10:00   
4    1031         70  2020      1  Austrian Grand Prix 2020-07-05  13:10:00   

   qualifyId  driverId  constructorId  number        q1        q2        q3  \
0       8378       822            131      77  1:04.111  1:03.015  1:02.939   
1       8379         1            131      44  1:04.198  1:03.096  1:02.951   
2       8380       830              9      33  1:04.024  1:04.000  1:03.477   
3       8381       846              1       4  1:04.606  1:03.819  1:03.626   
4       8382       848              9      23  1:04.661  1:03.746  1:03.868   

   grid  before_race_points  before_race_position  before_race_wins  \
0     1                 0.0                   0.0               0.0   
1     2                 0.0                   0.0               0.0   
2     3                 0.0                   0.0               0.0   
3     4                 0.0                   0.0               0.0   
4     5                 0.0                   0.0               0.0   

   before_race_ctor_points  before_race_ctor_position  before_race_ctor_wins  \
0                      0.0                        0.0                    0.0   
1                      0.0                        0.0                    0.0   
2                      0.0                        0.0                    0.0   
3                      0.0                        0.0                    0.0   
4                      0.0                        0.0                    0.0   

         dob  race_time_ms    q1_ms    q2_ms    q3_ms  driver_age  
0 1989-08-28        790000  64111.0  63015.0  62939.0   30.852841  
1 1985-01-07        790000  64198.0  63096.0  62951.0   35.490760  
2 1997-09-30        790000  64024.0  64000.0  63477.0   22.762491  
3 1999-11-13        790000  64605.0  63819.0  63626.0   20.643395  
4 1996-03-23        790000  64661.0  63746.0  63868.0   24.284736

In [121]:
df['time'] = pd.to_datetime(df['time'], format='%H:%M:%S')

Kreiramo feature doba dana trke - ujutru, popodne, uvece. To radimo tako što ćemo iz time kolone izvesti hour.

In [122]:
def part_of_day(h):
    if 6 <= h < 12:
        return "morning"
    elif 12 <= h < 18:
        return "afternoon"
    else:
        return "evening"

In [123]:
df['hour'] = df['time'].dt.hour
df['race_part_of_day'] = df['hour'].apply(part_of_day)

Ovde ću da kreiram novi feature koji označava u kom q delu je vozač ispao. 1-q1, 2-q2, 3-q3.

In [124]:
def get_round(row):
    if pd.isna(row['q2']):
        return 1 # ispao u q1
    elif pd.isna(row['q3']):
        return 2 # ispao u q2
    else:
        return 3 # dosao u q3

In [125]:
df['qualifying_round'] = df.apply(get_round ,axis=1)

In [126]:
df.head()

raceId  circuitId  year  round                 name       date  \
0    1031         70  2020      1  Austrian Grand Prix 2020-07-05   
1    1031         70  2020      1  Austrian Grand Prix 2020-07-05   
2    1031         70  2020      1  Austrian Grand Prix 2020-07-05   
3    1031         70  2020      1  Austrian Grand Prix 2020-07-05   
4    1031         70  2020      1  Austrian Grand Prix 2020-07-05   

                 time  qualifyId  driverId  constructorId  number        q1  \
0 1900-01-01 13:10:00       8378       822            131      77  1:04.111   
1 1900-01-01 13:10:00       8379         1            131      44  1:04.198   
2 1900-01-01 13:10:00       8380       830              9      33  1:04.024   
3 1900-01-01 13:10:00       8381       846              1       4  1:04.606   
4 1900-01-01 13:10:00       8382       848              9      23  1:04.661   

         q2        q3  grid  before_race_points  before_race_position  \
0  1:03.015  1:02.939     1                 0.0                   0.0   
1  1:03.096  1:02.951     2                 0.0                   0.0   
2  1:04.000  1:03.477     3                 0.0                   0.0   
3  1:03.819  1:03.626     4                 0.0                   0.0   
4  1:03.746  1:03.868     5                 0.0                   0.0   

   before_race_wins  before_race_ctor_points  before_race_ctor_position  \
0               0.0                      0.0                        0.0   
1               0.0                      0.0                        0.0   
2               0.0                      0.0                        0.0   
3               0.0                      0.0                        0.0   
4               0.0                      0.0                        0.0   

   before_race_ctor_wins        dob  race_time_ms    q1_ms    q2_ms    q3_ms  \
0                    0.0 1989-08-28        790000  64111.0  63015.0  62939.0   
1                    0.0 1985-01-07        790000  64198.0  63096.0  62951.0   
2                    0.0 1997-09-30        790000  64024.0  64000.0  63477.0   
3                    0.0 1999-11-13        790000  64605.0  63819.0  63626.0   
4                    0.0 1996-03-23        790000  64661.0  63746.0  63868.0   

   driver_age  hour race_part_of_day  qualifying_round  
0   30.852841    13        afternoon                 3  
1   35.490760    13        afternoon                 3  
2   22.762491    13        afternoon                 3  
3   20.643395    13        afternoon                 3  
4   24.284736    13        afternoon                 3

In [127]:
results = results[results['raceId'] >= 1031]

In [128]:
results = results.replace("\\N", np.nan)
results.isna().sum()

resultId             0
raceId               0
driverId             0
constructorId        0
number               0
grid                 0
position           271
positionText         0
positionOrder        0
points               0
laps                 0
time               860
milliseconds       860
fastestLap         109
rank                 0
fastestLapTime     109
fastestLapSpeed    109
statusId             0
dtype: int64

In [129]:
results = results[['raceId', 'driverId', 'constructorId', 'positionText', 'rank']]
df = df.merge(results, on=['raceId', 'driverId', 'constructorId'], how='left')
df.shape

(2138, 32)

Ovde kreiramo kolonu najbrži krug bonus, koja označava koji vozač je uzeo najbrži krug. - DATA LEAKAGE?

In [130]:
# df['fastest_lap_bonus'] = df['rank'].apply(lambda x: 1 if x == 1 else 0)

Ovde kreiramo ciljanu promenljivu

In [131]:
print(df['positionText'].unique())

df['final_position_num'] = pd.to_numeric(df['positionText'], errors='coerce')
print(df['final_position_num'].unique())

['1' '4' 'R' '3' '13' '6' '2' '5' '10' '7' '12' '8' '9' '11' '15' '16'
 '17' '14' '18' '19' 'W' '20' 'D']
[ 1.  4. nan  3. 13.  6.  2.  5. 10.  7. 12.  8.  9. 11. 15. 16. 17. 14.
 18. 19. 20.]


In [132]:
df['scored_points'] = df['final_position_num'].apply(lambda x: 1 if x <= 10 else 0)
df['scored_points'].unique()

array([1, 0], dtype=int64)

In [133]:
df.head()

raceId  circuitId  year  round                 name       date  \
0    1031         70  2020      1  Austrian Grand Prix 2020-07-05   
1    1031         70  2020      1  Austrian Grand Prix 2020-07-05   
2    1031         70  2020      1  Austrian Grand Prix 2020-07-05   
3    1031         70  2020      1  Austrian Grand Prix 2020-07-05   
4    1031         70  2020      1  Austrian Grand Prix 2020-07-05   

                 time  qualifyId  driverId  constructorId  number        q1  \
0 1900-01-01 13:10:00       8378       822            131      77  1:04.111   
1 1900-01-01 13:10:00       8379         1            131      44  1:04.198   
2 1900-01-01 13:10:00       8380       830              9      33  1:04.024   
3 1900-01-01 13:10:00       8381       846              1       4  1:04.606   
4 1900-01-01 13:10:00       8382       848              9      23  1:04.661   

         q2        q3  grid  before_race_points  before_race_position  \
0  1:03.015  1:02.939     1                 0.0                   0.0   
1  1:03.096  1:02.951     2                 0.0                   0.0   
2  1:04.000  1:03.477     3                 0.0                   0.0   
3  1:03.819  1:03.626     4                 0.0                   0.0   
4  1:03.746  1:03.868     5                 0.0                   0.0   

   before_race_wins  before_race_ctor_points  before_race_ctor_position  \
0               0.0                      0.0                        0.0   
1               0.0                      0.0                        0.0   
2               0.0                      0.0                        0.0   
3               0.0                      0.0                        0.0   
4               0.0                      0.0                        0.0   

   before_race_ctor_wins        dob  race_time_ms    q1_ms    q2_ms    q3_ms  \
0                    0.0 1989-08-28        790000  64111.0  63015.0  62939.0   
1                    0.0 1985-01-07        790000  64198.0  63096.0  62951.0   
2                    0.0 1997-09-30        790000  64024.0  64000.0  63477.0   
3                    0.0 1999-11-13        790000  64605.0  63819.0  63626.0   
4                    0.0 1996-03-23        790000  64661.0  63746.0  63868.0   

   driver_age  hour race_part_of_day  qualifying_round positionText rank  \
0   30.852841    13        afternoon                 3            1    2   
1   35.490760    13        afternoon                 3            4    3   
2   22.762491    13        afternoon                 3            R   15   
3   20.643395    13        afternoon                 3            3    1   
4   24.284736    13        afternoon                 3           13    7   

   final_position_num  scored_points  
0                 1.0              1  
1                 4.0              1  
2                 NaN              0  
3                 3.0              1  
4                13.0              0

<b>year</b> - godina trke <br>
<b>round</b> - koja je runda u pitanju - trka <br>
<b>date</b> - datum trke <br>
<b>time</b> - vreme trke <br>
<b>number</b> - broj vozača <br>
<b>grid</b> - pozicija sa koje vozač startuje <br>
<b>before_race_(points, position, wins)</b> - koliko posmatrani vozač ima poena, na kojoj se poziciji nalazi (na nivou šampionata - godine) i koliko ima pobeda do sada - tj. do tekuće trke <br>
<b>before_race_ctor(points, position, wins)</b> - isto kao i za vozače, samo za konstruktore <br>
<b>name_(naziv staze)</b> - ohe staze<br>
<b>q1 q2 q3</b> - vremena za q1, q2 i q3 <br>
<b>race_time_ms</b> - vreme trke u milisekundama
<b>hour</b> - u koliko h počinje trka <br>
<b>race_part_of_day</b> - oh morning, afternoon, evening<br>
<b>qulifying_round</b> - u kom delu je vozač ispao 3 - došao do q3, 2 - došao do q2 i ispao, 1 - ispao u q1 <br>
<b>positionText</b> - osvojeno mesto ima i R, W i još nešto <b> - ZA BRISANJE?</b><br>
<b>rank</b> - koji vozač je uzeo najbrži krug - 1 najbolje vreme -> 20<b> - ZA BRISANJE?</b><br>
<b>fastest_lap_bonus</b> - ko je uzeo najbrži krug [0,1]<b> - ZA BRISANJE?</b><br>
<b>final_position_num</b> - krajnjna mesta - ima NaN - nije završio<b> - ZA BRISANJE?</b> ili da se ostavi kao feature, za prethodni krug<br>
<b>scored_points</b> - ciljana promenljiva - vozač ostvario bodovi ili nije [0,1]<b> - y</b><br>


In [134]:
df.isna().sum()

raceId                          0
circuitId                       0
year                            0
round                           0
name                            0
date                            0
time                            0
qualifyId                       0
driverId                        0
constructorId                   0
number                          0
q1                             21
q2                            551
q3                           1093
grid                            0
before_race_points             15
before_race_position           15
before_race_wins               15
before_race_ctor_points         8
before_race_ctor_position       8
before_race_ctor_wins           8
dob                             0
race_time_ms                    0
q1_ms                          21
q2_ms                         551
q3_ms                        1093
driver_age                      0
hour                            0
race_part_of_day                0
qualifying_rou

In [135]:
df.describe()

raceId    circuitId         year        round  \
count  2138.000000  2138.000000  2138.000000  2138.000000   
mean   1088.503742    32.559869  2022.130496    11.333957   
min    1031.000000     1.000000  2020.000000     1.000000   
25%    1060.000000     9.000000  2021.000000     6.000000   
50%    1088.000000    21.000000  2022.000000    11.000000   
75%    1118.000000    70.000000  2023.000000    17.000000   
max    1144.000000    80.000000  2024.000000    24.000000   
std      33.241142    28.463975     1.388264     6.370320   

                                date                           time  \
count                           2138                           2138   
mean   2022-09-22 20:24:28.288119808  1900-01-01 13:34:40.636108544   
min              2020-07-05 00:00:00            1900-01-01 04:00:00   
25%              2021-07-18 00:00:00            1900-01-01 13:00:00   
50%              2022-09-04 00:00:00            1900-01-01 13:00:00   
75%              2023-11-05 00:00:00            1900-01-01 15:00:00   
max              2024-12-08 00:00:00            1900-01-01 20:00:00   
std                              NaN                            NaN   

          qualifyId     driverId  constructorId       number         grid  \
count   2138.000000  2138.000000    2138.000000  2138.000000  2138.000000   
mean    9473.799813   719.040692      92.881665    27.799345    10.491113   
min     8378.000000     1.000000       1.000000     1.000000     1.000000   
25%     8929.250000   817.000000       6.000000    10.000000     5.250000   
50%     9482.500000   839.000000      51.000000    20.000000    10.000000   
75%    10016.750000   847.000000     210.000000    44.000000    15.000000   
max    10551.000000   862.000000     215.000000    99.000000    20.000000   
std      627.704242   290.465754      89.355219    24.224605     5.762997   

       before_race_points  before_race_position  before_race_wins  \
count         2123.000000           2123.000000       2123.000000   
mean            58.942770             10.526613          0.554404   
min              0.000000              0.000000          0.000000   
25%              3.500000              5.000000          0.000000   
50%             22.000000             10.000000          0.000000   
75%             83.000000             16.000000          0.000000   
max            575.000000             23.000000         19.000000   
std             82.631161              6.013700          1.833615   

       before_race_ctor_points  before_race_ctor_position  \
count              2130.000000                2130.000000   
mean                117.778873                   5.441784   
min                   0.000000                   0.000000   
25%                   8.000000                   3.000000   
50%                  46.000000                   5.000000   
75%                 163.000000                   8.000000   
max                 860.000000                  10.000000   
std                 158.029901                   2.909572   

       before_race_ctor_wins                            dob  race_time_ms  \
count            2130.000000                           2138  2.138000e+03   
mean                1.114554  1994-04-03 17:03:05.219831552  8.146773e+05   
min                 0.000000            1979-10-17 00:00:00  2.400000e+05   
25%                 0.000000            1989-08-28 00:00:00  7.800000e+05   
50%                 0.000000            1996-02-07 00:00:00  7.800000e+05   
75%                 0.000000            1998-10-29 00:00:00  9.000000e+05   
max                21.000000            2005-05-08 00:00:00  1.200000e+06   
std                 2.878146                            NaN  2.073265e+05   

               q1_ms          q2_ms          q3_ms   driver_age         hour  \
count    2117.000000    1587.000000    1045.000000  2138.000000  2138.000000   
mean    85496.521020   84519.494014   84150.616268    28.471293    13.537418   
min     53904.000000  

In [136]:
df.dtypes

raceId                                int64
circuitId                             int64
year                                  int64
round                                 int64
name                                 object
date                         datetime64[ns]
time                         datetime64[ns]
qualifyId                             int64
driverId                              int64
constructorId                         int64
number                                int64
q1                                   object
q2                                   object
q3                                   object
grid                                  int64
before_race_points                  float64
before_race_position                float64
before_race_wins                    float64
before_race_ctor_points             float64
before_race_ctor_position           float64
before_race_ctor_wins               float64
dob                          datetime64[ns]
race_time_ms                    

# Helper functions

Function for evaluation

In [137]:
def evaluate_classifier(model_name, y_true, y_pred, y_proba=None):
    print('==========', model_name, '==========')

    acc = accuracy_score(y_true, y_pred)
    prec = precision_score(y_true, y_pred, zero_division=0)
    rec = recall_score(y_true, y_pred, zero_division=0)
    f1 = f1_score(y_true, y_pred, zero_division=0)

    print(f'Accuracy : {acc:.4f}')
    print(f'Precision: {prec:.4f}')
    print(f'Recall   : {rec:.4f}')
    print(f'F1-score : {f1:.4f}')

    if y_proba is not None:
        roc = roc_auc_score(y_true, y_proba)
        print(f'ROC-AUC  : {roc:.4f}')

    print('Confusion matrix:')
    print(confusion_matrix(y_true, y_pred), '\n')

Function that return amount of points for given position

In [138]:
points_map = {
    '1': 25,
    '2': 18,
    '3': 15,
    '4': 12,
    '5': 10,
    '6': 8,
    '7': 6,
    '8': 4,
    '9': 2,
    '10': 1
}

def points_for_position(pos):
    return points_map.get(pos, 0)

# First model training and testing

In [139]:
# !pip install xgboost
# !pip install lightgbm - nije instaliran

In [140]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

In [141]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix
)

#### Time based split - HOLD-OUT

In [142]:
train_df = df[df['year'] <= 2023]
test_df  = df[df['year'] == 2024]

In [143]:
y = df['scored_points']
y.mean()

0.500467726847521

In [144]:
test_df.head()

raceId  circuitId  year  round                name       date  \
1659    1121          3  2024      1  Bahrain Grand Prix 2024-03-02   
1660    1121          3  2024      1  Bahrain Grand Prix 2024-03-02   
1661    1121          3  2024      1  Bahrain Grand Prix 2024-03-02   
1662    1121          3  2024      1  Bahrain Grand Prix 2024-03-02   
1663    1121          3  2024      1  Bahrain Grand Prix 2024-03-02   

                    time  qualifyId  driverId  constructorId  number  \
1659 1900-01-01 15:00:00      10073       830              9       1   
1660 1900-01-01 15:00:00      10074       844              6      16   
1661 1900-01-01 15:00:00      10075       847            131      63   
1662 1900-01-01 15:00:00      10076       832              6      55   
1663 1900-01-01 15:00:00      10077       815              9      11   

            q1        q2        q3  grid  before_race_points  \
1659  1:30.031  1:29.374  1:29.179     1               575.0   
1660  1:30.243  1:29.165  1:29.407     2               206.0   
1661  1:30.350  1:29.922  1:29.485     3               175.0   
1662  1:29.909  1:29.573  1:29.507     4               200.0   
1663  1:30.221  1:29.932  1:29.537     5               285.0   

      before_race_position  before_race_wins  before_race_ctor_points  \
1659                   1.0              19.0                    860.0   
1660                   5.0               0.0                    406.0   
1661                   8.0               0.0                    409.0   
1662                   7.0               1.0                    406.0   
1663                   2.0               2.0                    860.0   

      before_race_ctor_position  before_race_ctor_wins        dob  \
1659                        1.0                   21.0 1997-09-30   
1660                        3.0                    1.0 1997-10-16   
1661                        2.0                    0.0 1998-02-15   
1662                        3.0                    1.0 1994-09-01   
1663                        1.0                   21.0 1990-01-26   

      race_time_ms    q1_ms    q2_ms    q3_ms  driver_age  hour  \
1659        900000  90031.0  89374.0  89179.0   26.420260    15   
1660        900000  90243.0  89164.0  89407.0   26.376454    15   
1661        900000  90350.0  89922.0  89485.0   26.042437    15   
1662        900000  89908.0  89573.0  89507.0   29.500342    15   
1663        900000  90221.0  89932.0  89537.0   34.097194    15   

     race_part_of_day  qualifying_round positionText rank  final_position_num  \
1659        afternoon                 3            1    1                 1.0   
1660        afternoon                 3            4    2                 4.0   
1661        afternoon                 3            5   12                 5.0   
1662        afternoon                 3            3    6                 3.0   
1663        afternoon                 3            2    4                 2.0   

      scored_points  
1659              1  
1660              1  
1661              1  
1662              1  
1663              1

In [145]:
X_train = train_df.drop(columns=['raceId', 'circuitId', 'year', 'date', 'time', 'qualifyId', 'driverId', 'constructorId',
                     'number', 'q1', 'q2', 'q3', 'dob', 'race_time_ms', 'q1_ms', 'q2_ms', 'q3_ms', 'hour',
                     'positionText', 'rank', 'final_position_num', 'scored_points', 'qualifying_round', 'grid'])
y_train = train_df['scored_points']

X_test = test_df.drop(columns=['raceId', 'circuitId', 'year', 'date', 'time', 'qualifyId', 'driverId', 'constructorId',
                     'number', 'q1', 'q2', 'q3', 'dob', 'race_time_ms', 'q1_ms', 'q2_ms', 'q3_ms', 'hour',
                     'positionText', 'rank', 'final_position_num', 'scored_points', 'qualifying_round', 'grid'])
y_test = test_df['scored_points']

#### Pipelines

Needs to be updated every time a new feature is added.

In [146]:
categorical_cols = X_train.select_dtypes(include=['object']).columns.tolist()
numerical_cols = X_train.select_dtypes(include=['number']).columns.tolist()

In [147]:
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numerical_cols),
        ('cat', categorical_transformer, categorical_cols)
    ]
)

In [148]:
pipeline_hd_log_reg = Pipeline(steps=[
    ("preprocessing", preprocessor),
    ("model", LogisticRegression())
])

pipeline_hd_rf =Pipeline(steps=[
    ("preprocessing", preprocessor),
    ("model", RandomForestClassifier())
])

pipeline_hd_xgb =Pipeline(steps=[
    ("preprocessing", preprocessor),
    ("model", XGBClassifier())
])

In [149]:
pipelines = {
    "Logistic Regression": pipeline_hd_log_reg,
    "Random Forest": pipeline_hd_rf,
    "XGBoost": pipeline_hd_xgb
}

#### First model evaluation

In [150]:
for name, pipeline in pipelines.items():
    print(f"\nTraining {name} ...")

    pipeline.fit(X_train, y_train)

    y_pred = pipeline.predict(X_test)

    y_proba = pipeline.predict_proba(X_test)[:, 1]

    evaluate_classifier(
        model_name=name,
        y_true=y_test,
        y_pred=y_pred,
        y_proba=y_proba
    )


Training Logistic Regression ...
========== Logistic Regression ==========
Accuracy : 0.8058
Precision: 0.8267
Recall   : 0.7750
F1-score : 0.8000
ROC-AUC  : 0.8591
Confusion matrix:
[[200  39]
 [ 54 186]] 


Training Random Forest ...
========== Random Forest ==========
Accuracy : 0.7745
Precision: 0.7705
Recall   : 0.7833
F1-score : 0.7769
ROC-AUC  : 0.8387
Confusion matrix:
[[183  56]
 [ 52 188]] 


Training XGBoost ...
========== XGBoost ==========
Accuracy : 0.7140
Precision: 0.6958
Recall   : 0.7625
F1-score : 0.7276
ROC-AUC  : 0.7919
Confusion matrix:
[[159  80]
 [ 57 183]] 



#### Time-based split - Expanding window

In [151]:
y = 'scored_points'
cols_to_drop = ['raceId', 'circuitId', 'year', 'date', 'time', 'qualifyId', 'driverId', 'constructorId',
                     'number', 'q1', 'q2', 'q3', 'dob', 'race_time_ms', 'q1_ms', 'q2_ms', 'q3_ms', 'hour',
                     'positionText', 'rank', 'final_position_num', 'scored_points', 'qualifying_round', 'grid']
features = [c for c in df.columns if c not in cols_to_drop]

In [152]:
from sklearn.base import clone

years = sorted(df['year'].unique())

for i in range(1, len(years)):
    train_years = years[:i]
    test_years = years[i]

    train_df = df[df['year'].isin(train_years)]
    test_df = df[df['year'] == test_years]

    X_train = train_df[features]
    y_train = train_df[y]

    X_test = test_df[features]
    y_test = test_df[y]

    models = clone(pipelines)

    print('============= Iteration ', i, ' =============')
    for name, model in models.items():
        print(f"\nTraining {name} ...")
    
        model.fit(X_train, y_train)
    
        y_pred = model.predict(X_test)
    
        y_proba = model.predict_proba(X_test)[:, 1]
    
        evaluate_classifier(
            model_name=name,
            y_true=y_test,
            y_pred=y_pred,
            y_proba=y_proba
        )
        

============= Iteration  1  =============

Training Logistic Regression ...
========== Logistic Regression ==========
Accuracy : 0.7585
Precision: 0.7794
Recall   : 0.7227
F1-score : 0.7500
ROC-AUC  : 0.8217
Confusion matrix:
[[174  45]
 [ 61 159]] 


Training Random Forest ...
========== Random Forest ==========
Accuracy : 0.7153
Precision: 0.6715
Recall   : 0.8455
F1-score : 0.7485
ROC-AUC  : 0.7905
Confusion matrix:
[[128  91]
 [ 34 186]] 


Training XGBoost ...
========== XGBoost ==========
Accuracy : 0.6856
Precision: 0.6653
Recall   : 0.7500
F1-score : 0.7051
ROC-AUC  : 0.7416
Confusion matrix:
[[136  83]
 [ 55 165]] 

============= Iteration  2  =============

Training Logistic Regression ...
========== Logistic Regression ==========
Accuracy : 0.7250
Precision: 0.7346
Recall   : 0.7045
F1-score : 0.7193
ROC-AUC  : 0.7742
Confusion matrix:
[[164  56]
 [ 65 155]] 


Training Random Forest ...
========== Random Forest ==========
Accuracy : 0.6955
Precision: 0.6706
Recall   : 0.768

# Second model - upgrade

Feature engineering <br>
<b>Driver's form</b>, maybe to add features like: points in previous 3/5 races, average position in last n races, percentage races in points in last n races. <br>
Also with constructors <br>
<b>Track-specific performance</b> - historical driver's/ctor's performance on track. 
driver_avg_finish_on_track, 
driver_points_rate_on_track, 
ctor_points_rate_on_track <br>
<b> Race </b>: is_street_circuit, track_length, laps_count, safety_car_probability (proxy: street circuit + history), weather_risk (ako ne koristiš konkretno vreme) 

Maybe I should add fastest lap points.

In [153]:
df['fastest_lap'] = (df['rank'] == '1').astype(int)

df = df.sort_values(['driverId', 'year', 'round'])

df['fastest_lap_prev'] = (
    df
    .groupby('driverId')['fastest_lap']
    .shift(1)
)

df['fastest_lap_prev'] = df['fastest_lap_prev'].fillna(0)

In [154]:
# 830 -> Max Verstapen
df[df['driverId'] == 830].head()
#df['rank'].unique()
#df['fastest_lap'].unique()

raceId  circuitId  year  round                         name       date  \
2     1031         70  2020      1          Austrian Grand Prix 2020-07-05   
21    1032         70  2020      2           Styrian Grand Prix 2020-07-12   
45    1033         11  2020      3         Hungarian Grand Prix 2020-07-19   
62    1034          9  2020      4           British Grand Prix 2020-08-02   
83    1035          9  2020      5  70th Anniversary Grand Prix 2020-08-09   

                  time  qualifyId  driverId  constructorId  number        q1  \
2  1900-01-01 13:10:00       8380       830              9      33  1:04.024   
21 1900-01-01 13:10:00       8399       830              9      33  1:18.297   
45 1900-01-01 13:10:00       8423       830              9      33  1:15.495   
62 1900-01-01 13:10:00       8440       830              9      33  1:26.115   
83 1900-01-01 13:10:00       8461       830              9      33  1:27.154   

          q2        q3  grid  before_race_points  before_race_position  \
2   1:04.000  1:03.477     3                 0.0                   0.0   
21  1:17.938  1:20.489     2                 0.0                  20.0   
45  1:14.976  1:14.849     7                15.0                   6.0   
62  1:26.144  1:25.325     3                33.0                   3.0   
83  1:26.779  1:26.176     4                52.0                   3.0   

    before_race_wins  before_race_ctor_points  before_race_ctor_position  \
2                0.0                      0.0                        0.0   
21               0.0                      0.0                        9.0   
45               0.0                     27.0                        3.0   
62               0.0                     55.0                        2.0   
83               0.0                     78.0                        2.0   

    before_race_ctor_wins        dob  race_time_ms    q1_ms    q2_ms    q3_ms  \
2                     0.0 1997-09-30        790000  64024.0  64000.0  63477.0   
21                    0.0 1997-09-30        790000  78297.0  77938.0  80489.0   
45                    0.0 1997-09-30        790000  75495.0  74976.0  74849.0   
62                    0.0 1997-09-30        790000  86115.0  86144.0  85325.0   
83                    0.0 1997-09-30        790000  87154.0  86779.0  86176.0   

    driver_age  hour race_part_of_day  qualifying_round positionText rank  \
2    22.762491    13        afternoon                 3            R   15   
21   22.781656    13        afternoon                 3            3    2   
45   22.800821    13        afternoon                 3            2    4   
62   22.839151    13        afternoon                 3            2    1   
83   22.858316    13        afternoon                 3            1    2   

    final_position_num  scored_points  fastest_lap  fastest_lap_prev  
2                  NaN              0            0               0.0  
21                 3.0              1            0               0.0  
45                 2.0              1            0               0.0  
62                 2.0              1            1               0.0  
83                 1.0              1            0               1.0

In [155]:
df['points'] = df['positionText'].apply(points_for_position)
df['points_total'] = df['points'] + df['fastest_lap']

In [156]:
df.head()

raceId  circuitId  year  round                         name       date  \
1     1031         70  2020      1          Austrian Grand Prix 2020-07-05   
20    1032         70  2020      2           Styrian Grand Prix 2020-07-12   
59    1033         11  2020      3         Hungarian Grand Prix 2020-07-19   
60    1034          9  2020      4           British Grand Prix 2020-08-02   
81    1035          9  2020      5  70th Anniversary Grand Prix 2020-08-09   

                  time  qualifyId  driverId  constructorId  number        q1  \
1  1900-01-01 13:10:00       8379         1            131      44  1:04.198   
20 1900-01-01 13:10:00       8398         1            131      44  1:18.188   
59 1900-01-01 13:10:00       8437         1            131      44  1:14.907   
60 1900-01-01 13:10:00       8438         1            131      44  1:25.900   
81 1900-01-01 13:10:00       8459         1            131      44  1:26.818   

          q2        q3  grid  before_race_points  before_race_position  \
1   1:03.096  1:02.951     2                 0.0                   0.0   
20  1:17.825  1:19.273     1                12.0                   4.0   
59  1:14.261  1:13.447     1                37.0                   2.0   
60  1:25.347  1:24.303     1                63.0                   1.0   
81  1:26.266  1:25.217     2                88.0                   1.0   

    before_race_wins  before_race_ctor_points  before_race_ctor_position  \
1                0.0                      0.0                        0.0   
20               0.0                     37.0                        1.0   
59               1.0                     80.0                        1.0   
60               2.0                    121.0                        1.0   
81               3.0                    146.0                        1.0   

    before_race_ctor_wins        dob  race_time_ms    q1_ms    q2_ms    q3_ms  \
1                     0.0 1985-01-07        790000  64198.0  63096.0  62951.0   
20                    1.0 1985-01-07        790000  78188.0  77825.0  79273.0   
59                    2.0 1985-01-07        790000  74907.0  74261.0  73447.0   
60                    3.0 1985-01-07        790000  85900.0  85347.0  84303.0   
81                    4.0 1985-01-07        790000  86818.0  86265.0  85217.0   

    driver_age  hour race_part_of_day  qualifying_round positionText rank  \
1    35.490760    13        afternoon                 3            4    3   
20   35.509925    13        afternoon                 3            1    3   
59   35.529090    13        afternoon                 3            1    1   
60   35.567420    13        afternoon                 3            1    3   
81   35.586585    13        afternoon                 3            2    1   

    final_position_num  scored_points  fastest_lap  fastest_lap_prev  points  \
1                  4.0              1            0               0.0      12   
20                 1.0              1            0               0.0      25   
59                 1.0              1            1               0.0      25   
60                 1.0              1            0               1.0      25   
81                 2.0              1            1               0.0      18   

    points_total  
1             12  
20            25  
59            26  
60            25  
81            19

In [157]:
df = df.sort_values(
    ['driverId', 'year', 'round']
).reset_index(drop=True)

In [158]:
# df['points_last_3'] = (
#     df
#     .groupby('driverId')['points_total']
#     .shift(1)
#     .rolling(window=3, min_periods=1)
#     .sum()
# )

df['points_last_3'] = (
    df
    .groupby('driverId')['points_total']
    .transform(lambda x: x.shift(1).rolling(3, min_periods=1).sum())
)

In [159]:
# df['points_last_5'] = (
#      df
#     .groupby('driverId')['points_total']
#     .shift(1)
#     .rolling(window=5, min_periods=1)
#     .sum()
# )   

df['points_last_5'] = (
    df
    .groupby('driverId')['points_total']
    .transform(lambda x: x.shift(1).rolling(5, min_periods=1).sum())
)

In final_position_num, we have missing values. They represent drivers who did not finish the race. So we will put 21.

In [160]:
df['final_position_num'].isna().sum()

271

In [161]:
df.head()

raceId  circuitId  year  round                         name       date  \
0    1031         70  2020      1          Austrian Grand Prix 2020-07-05   
1    1032         70  2020      2           Styrian Grand Prix 2020-07-12   
2    1033         11  2020      3         Hungarian Grand Prix 2020-07-19   
3    1034          9  2020      4           British Grand Prix 2020-08-02   
4    1035          9  2020      5  70th Anniversary Grand Prix 2020-08-09   

                 time  qualifyId  driverId  constructorId  number        q1  \
0 1900-01-01 13:10:00       8379         1            131      44  1:04.198   
1 1900-01-01 13:10:00       8398         1            131      44  1:18.188   
2 1900-01-01 13:10:00       8437         1            131      44  1:14.907   
3 1900-01-01 13:10:00       8438         1            131      44  1:25.900   
4 1900-01-01 13:10:00       8459         1            131      44  1:26.818   

         q2        q3  grid  before_race_points  before_race_position  \
0  1:03.096  1:02.951     2                 0.0                   0.0   
1  1:17.825  1:19.273     1                12.0                   4.0   
2  1:14.261  1:13.447     1                37.0                   2.0   
3  1:25.347  1:24.303     1                63.0                   1.0   
4  1:26.266  1:25.217     2                88.0                   1.0   

   before_race_wins  before_race_ctor_points  before_race_ctor_position  \
0               0.0                      0.0                        0.0   
1               0.0                     37.0                        1.0   
2               1.0                     80.0                        1.0   
3               2.0                    121.0                        1.0   
4               3.0                    146.0                        1.0   

   before_race_ctor_wins        dob  race_time_ms    q1_ms    q2_ms    q3_ms  \
0                    0.0 1985-01-07        790000  64198.0  63096.0  62951.0   
1                    1.0 1985-01-07        790000  78188.0  77825.0  79273.0   
2                    2.0 1985-01-07        790000  74907.0  74261.0  73447.0   
3                    3.0 1985-01-07        790000  85900.0  85347.0  84303.0   
4                    4.0 1985-01-07        790000  86818.0  86265.0  85217.0   

   driver_age  hour race_part_of_day  qualifying_round positionText rank  \
0   35.490760    13        afternoon                 3            4    3   
1   35.509925    13        afternoon                 3            1    3   
2   35.529090    13        afternoon                 3            1    1   
3   35.567420    13        afternoon                 3            1    3   
4   35.586585    13        afternoon                 3            2    1   

   final_position_num  scored_points  fastest_lap  fastest_lap_prev  points  \
0                 4.0              1            0               0.0      12   
1                 1.0              1            0               0.0      25   
2                 1.0              1            1               0.0      25   
3                 1.0              1            0               1.0      25   
4                 2.0              1            1               0.0      18   

   points_total  points_last_3  points_last_5  
0            12            NaN            NaN  
1            25           12.0           12.0  
2            26           37.0           37.0  
3            25           63.0           63.0  
4            19           76.0           88.0

In [162]:
df['final_position_num'] = df['final_position_num'].fillna(21)

# df['avg_pos_last_5'] = (
#     df
#     .groupby('driverId')['final_position_num']
#     .shift(1)
#     .rolling(5, min_periods=1)
#     .mean()
# )

df['avg_pos_last_5'] = (
    df
    .groupby('driverId')['final_position_num']
    .transform(lambda x: x.shift(1).rolling(5, min_periods=1).mean())
)

In [163]:
df[df['driverId'] == 1].head()

raceId  circuitId  year  round                         name       date  \
0    1031         70  2020      1          Austrian Grand Prix 2020-07-05   
1    1032         70  2020      2           Styrian Grand Prix 2020-07-12   
2    1033         11  2020      3         Hungarian Grand Prix 2020-07-19   
3    1034          9  2020      4           British Grand Prix 2020-08-02   
4    1035          9  2020      5  70th Anniversary Grand Prix 2020-08-09   

                 time  qualifyId  driverId  constructorId  number        q1  \
0 1900-01-01 13:10:00       8379         1            131      44  1:04.198   
1 1900-01-01 13:10:00       8398         1            131      44  1:18.188   
2 1900-01-01 13:10:00       8437         1            131      44  1:14.907   
3 1900-01-01 13:10:00       8438         1            131      44  1:25.900   
4 1900-01-01 13:10:00       8459         1            131      44  1:26.818   

         q2        q3  grid  before_race_points  before_race_position  \
0  1:03.096  1:02.951     2                 0.0                   0.0   
1  1:17.825  1:19.273     1                12.0                   4.0   
2  1:14.261  1:13.447     1                37.0                   2.0   
3  1:25.347  1:24.303     1                63.0                   1.0   
4  1:26.266  1:25.217     2                88.0                   1.0   

   before_race_wins  before_race_ctor_points  before_race_ctor_position  \
0               0.0                      0.0                        0.0   
1               0.0                     37.0                        1.0   
2               1.0                     80.0                        1.0   
3               2.0                    121.0                        1.0   
4               3.0                    146.0                        1.0   

   before_race_ctor_wins        dob  race_time_ms    q1_ms    q2_ms    q3_ms  \
0                    0.0 1985-01-07        790000  64198.0  63096.0  62951.0   
1                    1.0 1985-01-07        790000  78188.0  77825.0  79273.0   
2                    2.0 1985-01-07        790000  74907.0  74261.0  73447.0   
3                    3.0 1985-01-07        790000  85900.0  85347.0  84303.0   
4                    4.0 1985-01-07        790000  86818.0  86265.0  85217.0   

   driver_age  hour race_part_of_day  qualifying_round positionText rank  \
0   35.490760    13        afternoon                 3            4    3   
1   35.509925    13        afternoon                 3            1    3   
2   35.529090    13        afternoon                 3            1    1   
3   35.567420    13        afternoon                 3            1    3   
4   35.586585    13        afternoon                 3            2    1   

   final_position_num  scored_points  fastest_lap  fastest_lap_prev  points  \
0                 4.0              1            0               0.0      12   
1                 1.0              1            0               0.0      25   
2                 1.0              1            1               0.0      25   
3                 1.0              1            0               1.0      25   
4                 2.0              1            1               0.0      18   

   points_total  points_last_3  points_last_5  avg_pos_last_5  
0            12            NaN            NaN             NaN  
1            25           12.0           12.0            4.00  
2            26           37.0           37.0            2.50  
3            25           63.0           63.0            2.00  
4            19           76.0           88.0            1.75

We will fill first row with zeros (points_last_3,	points_last_5,	avg_pos_last_5).

In [164]:
df[['points_last_3', 'points_last_5', 'avg_pos_last_5']] = df[['points_last_3', 'points_last_5', 'avg_pos_last_5']].fillna(0)

Same features, just for constructors

In [165]:
team_race_points = (
    df
    .groupby(['constructorId', 'year', 'round'], as_index=False)
    .agg(team_points=('points_total', 'sum'))
)

In [166]:
team_race_points = team_race_points.sort_values(
    ['constructorId', 'year', 'round']
)

team_race_points['team_points_last_5'] = (
    team_race_points
    .groupby('constructorId')['team_points']
    .transform(lambda x: x.shift(1).rolling(5, min_periods=1).mean())
)

In [167]:
df = df.merge(
    team_race_points[
        ['constructorId', 'year', 'round', 'team_points_last_5']
    ],
    on=['constructorId', 'year', 'round'],
    how='left'
)

In [168]:
df[df['constructorId'] == 131].head()

raceId  circuitId  year  round                         name       date  \
0    1031         70  2020      1          Austrian Grand Prix 2020-07-05   
1    1032         70  2020      2           Styrian Grand Prix 2020-07-12   
2    1033         11  2020      3         Hungarian Grand Prix 2020-07-19   
3    1034          9  2020      4           British Grand Prix 2020-08-02   
4    1035          9  2020      5  70th Anniversary Grand Prix 2020-08-09   

                 time  qualifyId  driverId  constructorId  number        q1  \
0 1900-01-01 13:10:00       8379         1            131      44  1:04.198   
1 1900-01-01 13:10:00       8398         1            131      44  1:18.188   
2 1900-01-01 13:10:00       8437         1            131      44  1:14.907   
3 1900-01-01 13:10:00       8438         1            131      44  1:25.900   
4 1900-01-01 13:10:00       8459         1            131      44  1:26.818   

         q2        q3  grid  before_race_points  before_race_position  \
0  1:03.096  1:02.951     2                 0.0                   0.0   
1  1:17.825  1:19.273     1                12.0                   4.0   
2  1:14.261  1:13.447     1                37.0                   2.0   
3  1:25.347  1:24.303     1                63.0                   1.0   
4  1:26.266  1:25.217     2                88.0                   1.0   

   before_race_wins  before_race_ctor_points  before_race_ctor_position  \
0               0.0                      0.0                        0.0   
1               0.0                     37.0                        1.0   
2               1.0                     80.0                        1.0   
3               2.0                    121.0                        1.0   
4               3.0                    146.0                        1.0   

   before_race_ctor_wins        dob  race_time_ms    q1_ms    q2_ms    q3_ms  \
0                    0.0 1985-01-07        790000  64198.0  63096.0  62951.0   
1                    1.0 1985-01-07        790000  78188.0  77825.0  79273.0   
2                    2.0 1985-01-07        790000  74907.0  74261.0  73447.0   
3                    3.0 1985-01-07        790000  85900.0  85347.0  84303.0   
4                    4.0 1985-01-07        790000  86818.0  86265.0  85217.0   

   driver_age  hour race_part_of_day  qualifying_round positionText rank  \
0   35.490760    13        afternoon                 3            4    3   
1   35.509925    13        afternoon                 3            1    3   
2   35.529090    13        afternoon                 3            1    1   
3   35.567420    13        afternoon                 3            1    3   
4   35.586585    13        afternoon                 3            2    1   

   final_position_num  scored_points  fastest_lap  fastest_lap_prev  points  \
0                 4.0              1            0               0.0      12   
1                 1.0              1            0               0.0      25   
2                 1.0              1            1               0.0      25   
3                 1.0              1            0               1.0      25   
4                 2.0              1            1               0.0      18   

   points_total  points_last_3  points_last_5  avg_pos_last_5  \
0            12            0.0            0.0            0.00   
1            25           12.0           12.0            4.00   
2            26           37.0           37.0            2.50   
3            25           63.0           63.0            2.00   
4            19           76.0           88.0            1.75   

   team_points_last_5  
0                 NaN  
1           37.000000  
2           40.000000  
3           40.333333  
4           36.500000

In [169]:
# df[(df["final_position_num"] > 10) & (df["rank"] == 1)]
df['team_points_last_5'] = df['team_points_last_5'].fillna(0)

In [170]:
df = df.sort_values(['constructorId'])

In [171]:
df[
    ['constructorId', 'year', 'round', 'driverId', 'points_total']
].sort_values(['constructorId', 'year', 'round']).head()

constructorId  year  round  driverId  points_total
865               1  2020      1       832            10
1436              1  2020      1       846            16
866               1  2020      2       832             3
1437              1  2020      2       846            10
867               1  2020      3       832             2

#### Pipelines

In [180]:
cols_to_drop = ['raceId', 'circuitId', 'year', 'date', 'time', 'qualifyId', 'driverId', 'constructorId',
                     'number', 'q1', 'q2', 'q3', 'dob', 'race_time_ms', 'q1_ms', 'q2_ms', 'q3_ms', 'hour',
                     'positionText', 'rank', 'final_position_num', 'scored_points', 'qualifying_round', 
                     'grid', 'fastest_lap', 'points', 'points_total']
X = df.drop(columns=cols_to_drop)

In [181]:
categorical_cols = X.select_dtypes(include=['object']).columns.tolist()
numerical_cols = X.select_dtypes(include=['number']).columns.tolist()

In [182]:
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numerical_cols),
        ('cat', categorical_transformer, categorical_cols)
    ]
)

In [183]:
pipeline2_log_reg = Pipeline(steps=[
    ("preprocessing", preprocessor),
    ("model", LogisticRegression())
])

pipeline2_rf = Pipeline(steps=[
    ("preprocessing", preprocessor),
    ("model", RandomForestClassifier())
])

pipeline2_xgb = Pipeline(steps=[
    ("preprocessing", preprocessor),
    ("model", XGBClassifier())
])

In [184]:
pipelines = {
    "Logistic Regression": pipeline2_log_reg,
    "Random Forest": pipeline2_rf,
    "XGBoost": pipeline2_xgb
}

#### Evaluation for second models - only exp. window

In [189]:
print(df['scored_points'].unique())
df.head(1)

[1 0]


raceId  circuitId  year  round              name       date  \
1541    1143         78  2024     23  Qatar Grand Prix 2024-12-01   

                    time  qualifyId  driverId  constructorId  number  \
1541 1900-01-01 17:00:00      10514       846              1       4   

            q1        q2        q3  grid  before_race_points  \
1541  1:21.578  1:20.983  1:20.772     3               340.0   

      before_race_position  before_race_wins  before_race_ctor_points  \
1541                   2.0               3.0                    608.0   

      before_race_ctor_position  before_race_ctor_wins        dob  \
1541                        1.0                    5.0 1999-11-13   

      race_time_ms    q1_ms    q2_ms    q3_ms  driver_age  hour  \
1541       1020000  81578.0  80983.0  80771.0   25.051335    17   

     race_part_of_day  qualifying_round positionText rank  final_position_num  \
1541        afternoon                 3           10    1                10.0   

      scored_points  fastest_lap  fastest_lap_prev  points  points_total  \
1541              1            1               1.0       1             2   

      points_last_3  points_last_5  avg_pos_last_5  team_points_last_5  
1541           35.0           72.0             3.8                22.2

In [190]:
y = 'scored_points'
features = [c for c in df.columns if c not in cols_to_drop]

In [191]:
from sklearn.base import clone

years = sorted(df['year'].unique())

for i in range(1, len(years)):
    train_years = years[:i]
    test_years = years[i]

    train_df = df[df['year'].isin(train_years)]
    test_df = df[df['year'] == test_years]

    X_train = train_df[features]
    y_train = train_df[y]

    X_test = test_df[features]
    y_test = test_df[y]

    models = clone(pipelines)

    print('============= Iteration ', i, ' =============')
    for name, model in models.items():
        print(f"\nTraining {name} ...")
    
        model.fit(X_train, y_train)
    
        y_pred = model.predict(X_test)
    
        y_proba = model.predict_proba(X_test)[:, 1]
    
        evaluate_classifier(
            model_name=name,
            y_true=y_test,
            y_pred=y_pred,
            y_proba=y_proba
        )
        

============= Iteration  1  =============

Training Logistic Regression ...
========== Logistic Regression ==========
Accuracy : 0.7631
Precision: 0.7929
Recall   : 0.7136
F1-score : 0.7512
ROC-AUC  : 0.8249
Confusion matrix:
[[178  41]
 [ 63 157]] 


Training Random Forest ...
========== Random Forest ==========
Accuracy : 0.7244
Precision: 0.6827
Recall   : 0.8409
F1-score : 0.7536
ROC-AUC  : 0.7852
Confusion matrix:
[[133  86]
 [ 35 185]] 


Training XGBoost ...
========== XGBoost ==========
Accuracy : 0.6515
Precision: 0.6379
Recall   : 0.7045
F1-score : 0.6695
ROC-AUC  : 0.7005
Confusion matrix:
[[131  88]
 [ 65 155]] 

============= Iteration  2  =============

Training Logistic Regression ...
========== Logistic Regression ==========
Accuracy : 0.7136
Precision: 0.7156
Recall   : 0.7091
F1-score : 0.7123
ROC-AUC  : 0.7717
Confusion matrix:
[[158  62]
 [ 64 156]] 


Training Random Forest ...
========== Random Forest ==========
Accuracy : 0.7023
Precision: 0.6679
Recall   : 0.804

## Third model - hiperparameters optimization

In [194]:
from sklearn.model_selection import RandomizedSearchCV, TimeSeriesSplit
from scipy.stats import randint, uniform

In [197]:
pipeline3_lr = Pipeline(steps=[
    ("preprocessing", preprocessor),
    ("model", LogisticRegression())
])

pipeline3_rf = Pipeline(steps=[
    ("preprocessing", preprocessor),
    ("model", RandomForestClassifier())
])

pipeline3_xgb = Pipeline(steps=[
    ("preprocessing", preprocessor),
    ("model", XGBClassifier())
])

In [195]:
param_dist_lr = {
    "model__C": uniform(0.01, 10),  # C između 0.01 i 10
    "model__penalty": ["l1", "l2"],
    "model__solver": ["liblinear"]  # liblinear podržava L1 i L2
}

param_dist_rf = {
    "model__n_estimators": randint(100, 500),
    "model__max_depth": randint(5, 20),
    "model__min_samples_split": randint(2, 10),
    "model__min_samples_leaf": randint(1, 10)
}

param_dist_xgb = {
    "model__n_estimators": randint(100, 500),
    "model__max_depth": randint(3, 10),
    "model__learning_rate": uniform(0.01, 0.3),
    "model__subsample": uniform(0.6, 0.4)
}

In [211]:
y_string = 'scored_points'
X_strings = [c for c in df.columns if c not in cols_to_drop]

#### Evaluation

In [212]:
tscv = TimeSeriesSplit(n_splits=4)

search_lr = RandomizedSearchCV(
    estimator=pipeline3_lr,
    param_distributions=param_dist_lr,
    n_iter=20,
    scoring="roc_auc",
    cv=tscv,
    n_jobs=-1,
    random_state=42
)

search_rf = RandomizedSearchCV(
    estimator=pipeline3_rf,
    param_distributions=param_dist_rf,
    n_iter=20,
    scoring="roc_auc",
    cv=tscv,
    n_jobs=-1,
    random_state=42
)

search_xgb = RandomizedSearchCV(
    estimator=pipeline3_xgb,
    param_distributions=param_dist_xgb,
    n_iter=20,
    scoring="roc_auc",
    cv=tscv,
    n_jobs=-1,
    random_state=42
)

# ----------------------
# Fit i najbolji parametri
# ----------------------
X = df[X_strings]
y = df[y_string]

search_lr.fit(X, y)
print("Best Logistic Regression params:", search_lr.best_params_)

search_rf.fit(X, y)
print("Best Random Forest params:", search_rf.best_params_)

search_xgb.fit(X, y)
print("Best XGBoost params:", search_xgb.best_params_)

Best Logistic Regression params: {'model__C': 0.017787658410143285, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
Best Random Forest params: {'model__max_depth': 12, 'model__min_samples_leaf': 8, 'model__min_samples_split': 4, 'model__n_estimators': 249}
Best XGBoost params: {'model__learning_rate': 0.01691872751242473, 'model__max_depth': 5, 'model__n_estimators': 158, 'model__subsample': 0.7599443886861021}


C:\Users\Ogi\anaconda3\Lib\site-packages\xgboost\training.py:183: UserWarning: [21:31:32] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


In [213]:
# Logistic regression with best parameters
pipeline3_lr = Pipeline([
    ("preprocessing", preprocessor),
    ("model", LogisticRegression(
        C=0.017787658410143285,
        penalty='l2',
        solver='liblinear',
        random_state=42,
        max_iter=1000
    ))
])

# Random forest with best parameters
pipeline3_rf = Pipeline([
    ("preprocessing", preprocessor),
    ("model", RandomForestClassifier(
        n_estimators=120,
        max_depth=15,
        min_samples_split=6,
        min_samples_leaf=8,
        random_state=42
    ))
])

# XGBoost with best parameters
pipeline3_xgb = Pipeline([
    ("preprocessing", preprocessor),
    ("model", XGBClassifier(
        n_estimators=158,
        max_depth=5,
        learning_rate=0.01691872751242473,
        subsample=0.7599443886861021,
        random_state=42,
        use_label_encoder=False,
        eval_metric="logloss"
    ))
])

In [214]:
pipelines3 = {
    "Logistic Regression": pipeline3_lr,
    "Random Forest": pipeline3_rf,
    "XGBoost": pipeline3_xgb
}

In [215]:
years = sorted(df['year'].unique())

for i in range(1, len(years)):
    train_years = years[:i]
    test_years = years[i]

    train_df = df[df['year'].isin(train_years)]
    test_df = df[df['year'] == test_years]

    X_train = train_df[X_strings]
    y_train = train_df[y_string]

    X_test = test_df[X_strings]
    y_test = test_df[y_string]

    models = clone(pipelines3)

    print('============= Iteration ', i, ' =============')
    for name, model in models.items():
        print(f"\nTraining {name} ...")
    
        model.fit(X_train, y_train)
    
        y_pred = model.predict(X_test)
    
        y_proba = model.predict_proba(X_test)[:, 1]
    
        evaluate_classifier(
            model_name=name,
            y_true=y_test,
            y_pred=y_pred,
            y_proba=y_proba
        )
       

============= Iteration  1  =============

Training Logistic Regression ...
========== Logistic Regression ==========
Accuracy : 0.7494
Precision: 0.7806
Recall   : 0.6955
F1-score : 0.7356
ROC-AUC  : 0.8225
Confusion matrix:
[[176  43]
 [ 67 153]] 


Training Random Forest ...
========== Random Forest ==========
Accuracy : 0.7267
Precision: 0.6748
Recall   : 0.8773
F1-score : 0.7628
ROC-AUC  : 0.8019
Confusion matrix:
[[126  93]
 [ 27 193]] 


Training XGBoost ...
========== XGBoost ==========
Accuracy : 0.7130
Precision: 0.6767
Recall   : 0.8182
F1-score : 0.7407
ROC-AUC  : 0.7623
Confusion matrix:
[[133  86]
 [ 40 180]] 

============= Iteration  2  =============

Training Logistic Regression ...
========== Logistic Regression ==========
Accuracy : 0.7455
Precision: 0.7784
Recall   : 0.6864
F1-score : 0.7295
ROC-AUC  : 0.7874
Confusion matrix:
[[177  43]
 [ 69 151]] 


Training Random Forest ...


C:\Users\Ogi\anaconda3\Lib\site-packages\xgboost\training.py:183: UserWarning: [21:31:57] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


========== Random Forest ==========
Accuracy : 0.7273
Precision: 0.7033
Recall   : 0.7864
F1-score : 0.7425
ROC-AUC  : 0.7974
Confusion matrix:
[[147  73]
 [ 47 173]] 


Training XGBoost ...
========== XGBoost ==========
Accuracy : 0.6955
Precision: 0.6604
Recall   : 0.8045
F1-score : 0.7254
ROC-AUC  : 0.7774
Confusion matrix:
[[129  91]
 [ 43 177]] 

============= Iteration  3  =============

Training Logistic Regression ...
========== Logistic Regression ==========


C:\Users\Ogi\anaconda3\Lib\site-packages\xgboost\training.py:183: UserWarning: [21:31:58] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


Accuracy : 0.7659
Precision: 0.7910
Recall   : 0.7227
F1-score : 0.7553
ROC-AUC  : 0.8303
Confusion matrix:
[[178  42]
 [ 61 159]] 


Training Random Forest ...
========== Random Forest ==========
Accuracy : 0.7750
Precision: 0.7665
Recall   : 0.7909
F1-score : 0.7785
ROC-AUC  : 0.8247
Confusion matrix:
[[167  53]
 [ 46 174]] 


Training XGBoost ...
========== XGBoost ==========
Accuracy : 0.7591
Precision: 0.7478
Recall   : 0.7818
F1-score : 0.7644
ROC-AUC  : 0.8190
Confusion matrix:
[[162  58]
 [ 48 172]] 

============= Iteration  4  =============

Training Logistic Regression ...
========== Logistic Regression ==========
Accuracy : 0.8058
Precision: 0.8517
Recall   : 0.7417
F1-score : 0.7929
ROC-AUC  : 0.8597
Confusion matrix:
[[208  31]
 [ 62 178]] 


Training Random Forest ...


C:\Users\Ogi\anaconda3\Lib\site-packages\xgboost\training.py:183: UserWarning: [21:31:58] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


========== Random Forest ==========
Accuracy : 0.8058
Precision: 0.8267
Recall   : 0.7750
F1-score : 0.8000
ROC-AUC  : 0.8505
Confusion matrix:
[[200  39]
 [ 54 186]] 


Training XGBoost ...
========== XGBoost ==========
Accuracy : 0.7704
Precision: 0.7621
Recall   : 0.7875
F1-score : 0.7746
ROC-AUC  : 0.8458
Confusion matrix:
[[180  59]
 [ 51 189]] 



C:\Users\Ogi\anaconda3\Lib\site-packages\xgboost\training.py:183: UserWarning: [21:31:59] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
